// Code generated by "stringer -type=PacketType -output=packet_string.go"; DO NOT EDIT.

package fwpkt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketTypeUnknown-255]
	_ = x[PacketTypeDevInfo-1]
	_ = x[PacketTypeReadMemory-2]
	_ = x[PacketTypeMessage-3]
	_ = x[PacketTypeDevInfoResponse-129]
	_ = x[PacketTypeReadMemoryResponse-130]
	_ = x[PacketTypeMessageResponse-131]
}

const (
	_PacketType_name_0 = "PacketTypeDevInfoPacketTypeReadMemoryPacketTypeMessage"
	_PacketType_name_1 = "PacketTypeDevInfoResponsePacketTypeReadMemoryResponsePacketTypeMessageResponse"
	_PacketType_name_2 = "PacketTypeUnknown"
)

var (
	_PacketType_index_0 = [...]uint8{0, 17, 37, 54}
	_PacketType_index_1 = [...]uint8{0, 25, 53, 78}
)

func (i PacketType) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _PacketType_name_0[_PacketType_index_0[i]:_PacketType_index_0[i+1]]
	case 129 <= i && i <= 131:
		i -= 129
		return _PacketType_name_1[_PacketType_index_1[i]:_PacketType_index_1[i+1]]
	case i == 255:
		return _PacketType_name_2
	default:
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
